import type { Metadata } from "next";
import { AppProviders } from "@/components/app/AppProviders";
import { AppContainer } from "@/components/app/AppContainer";
import { Header } from "@/components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppProviders>
      <AppContainer>
        <Header />
        {children}
      </AppContainer>
    </AppProviders>
  );
}
