import type { Metadata } from "next";
import { AppProviders } from "@/components/app/AppProviders";
import { AppContainer } from "@/components/app/AppContainer";
import { Header } from "@/components/header/Header";
import { Modal } from "@/components/modal/Modal";

export const metadata: Metadata = {
  title: "ICAP",
  description: "Generated by Andrew Shmorhun",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppProviders>
      <AppContainer>
        <Header />

        {children}
      </AppContainer>
    </AppProviders>
  );
}
